abstract: An object-oriented Ogg Vorbis to decoder
author: EMERITUS
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Ogg-Vorbis-Decoder
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.005
version: 0.7
